app/urls.py
"""
------------------------------ GERAL ---------------------------------

"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacao.urls')), # URLs de Autenticação
    path('estoque/', include('estoque.urls')), # URLs de Estoque
    path('financeiro/', include('financeiro.urls')), # URLs de Financeiro

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

estoque/urls.py
"""
------------------------------ ESTOQUE ---------------------------------

"""

from django.contrib import admin
from django.urls import path
from .views import (
    AlimentoListView,
    AlimentoCreateView,
    AlimentoUpdateView,
    AlimentoDeleteView,
    UtilizarAlimentoView,
    EntradasListView,  
    SaidasListView,    
    # EntradasPDFView,   
    # SaidasPDFView,
    deslogar_view,
    financeiro_view,
    categoria_create, 
    itens_vencidos,
    
)

urlpatterns = [
    path('', AlimentoListView.as_view(), name='alimento_list'),  # Página principal listando os alimentos no estoque
    path('criar/', AlimentoCreateView.as_view(), name='alimento_create'),  # Adicionar novo alimento
    path('editar/<int:pk>/', AlimentoUpdateView.as_view(), name='alimento_update'),  # Editar alimento
    path('deletar/<int:pk>/', AlimentoDeleteView.as_view(), name='alimento_delete'),  # Deletar alimento
    path('utilizar/<int:pk>/', UtilizarAlimentoView.as_view(), name='utilizar_alimento'),  # Utilizar alimento (saída)
    path('entradas/', EntradasListView.as_view(), name='entradas_list'),  # Listar entradas
    path('saidas/', SaidasListView.as_view(), name='saidas_list'),  # Listar saídas
    path('categoria/criar/', categoria_create, name='categoria_create'),  # Adicionar nova categoria
    path('financeiro/', financeiro_view, name='financeiro'),
    path('deslogar/', deslogar_view, name='deslogar'),
    path('itens-vencidos/', itens_vencidos, name='itens_vencidos'),
    # path('entradas/pdf/', EntradasPDFView.as_view(), name='entradas_pdf'),  # Gerar PDF de entradas
    # path('saidas/pdf/', SaidasPDFView.as_view(), name='saidas_pdf'),  # Gerar PDF de saídas
    
]

estoque/models.py
from django.db import models
from django.utils import timezone


class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome


class Alimento(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='alimentos')
    referencia = models.CharField(max_length=100)
    nome = models.CharField(max_length=255)
    quantidade = models.IntegerField()
    peso = models.DecimalField(max_digits=10, decimal_places=2)
    validade = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data_entrada = models.DateField()
    nro_nota = models.CharField(max_length=100)
    nome_fornecedor = models.CharField(max_length=255)
    marca = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.nome} - {self.referencia}"


class Entrada(models.Model):
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE, related_name='entradas')
    quantidade = models.IntegerField()
    peso = models.DecimalField(max_digits=10, decimal_places=2)
    validade = models.DateField()
    data = models.DateField(default=timezone.now)  # Usando a data atual como padrão

    def __str__(self):
        return f"Entrada: {self.alimento.nome}"


class Saida(models.Model):
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE, related_name='saidas')
    quantidade = models.IntegerField()
    peso = models.DecimalField(max_digits=10, decimal_places=2)
    validade = models.DateField()
    data = models.DateField(default=timezone.now)  # Usando a data atual como padrão

    def __str__(self):
        return f"Saída: {self.alimento.nome}"

estoque/forms.py
from django import forms
from .models import Alimento, Categoria

class AlimentoForm(forms.ModelForm):
    class Meta:
        model = Alimento
        fields = [
            'categoria', 'referencia', 'nome', 'quantidade',
            'peso', 'validade', 'valor', 'data_entrada',
            'nro_nota', 'nome_fornecedor', 'marca'
        ]
        widgets = {
            'data_entrada': forms.DateInput(attrs={'type': 'date'}),
            'validade': forms.DateInput(attrs={'type': 'date'}),
        }



class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']

estoque/views.py
from decimal import Decimal
from django.contrib import messages
from django.contrib.auth import logout
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from xhtml2pdf import pisa  # Certifique-se de que a biblioteca xhtml2pdf está instalada
from datetime import datetime
from django.core.paginator import Paginator
from django.utils.dateparse import parse_date
from .models import Alimento, Entrada, Saida, Categoria  # Certifique-se que os modelos estão definidos corretamente
from .forms import AlimentoForm, CategoriaForm  # Certifique-se que os forms estão definidos



def deslogar_view(request):
    logout(request)  # Desloga o usuário
    return redirect('sigin')  # Redireciona para a página de login (ou qualquer outra página)

def financeiro_view(request):
    # Adicione qualquer lógica que precisar aqui
    return render(request, 'financeiro.html')  # Isso vai renderizar o template financeiro.html

def categoria_create(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria Criada com Sucesso!')
            return redirect('alimento_list')  # Redireciona para a lista de alimentos após a criação
    else:
        form = CategoriaForm()

    return render(request, 'estoque/categoria_form.html', {'form': form})  # Renderiza um template específico para a criação


def itens_vencidos(request):
    # Obtém a data atual
    data_atual = timezone.now().date()
    
    # Obtém todas as categorias
    categorias = Categoria.objects.all()
    
    # Obtém a categoria selecionada, se houver
    categoria_selecionada = request.GET.get('categoria', None)
    
    # Filtra os itens vencidos
    if categoria_selecionada:
        itens_vencidos = Alimento.objects.filter(validade__lt=data_atual, categoria_id=categoria_selecionada)
    else:
        itens_vencidos = Alimento.objects.filter(validade__lt=data_atual)

    # Contagem de itens vencidos por categoria
    itens_por_categoria = {categoria.id: Alimento.objects.filter(validade__lt=data_atual, categoria=categoria).count() for categoria in categorias}

    # Total de itens vencidos na categoria selecionada ou todos os itens vencidos
    total_itens_vencidos_categoria = itens_por_categoria.get(int(categoria_selecionada), 0) if categoria_selecionada else itens_vencidos.count()

    # Paginação
    page_number = request.GET.get('page', 1)  # Obtém o número da página atual, padrão é 1
    paginator = Paginator(itens_vencidos, 10)  # 10 itens por página
    page_obj = paginator.get_page(page_number)  # Obtém a página correspondente

    # Obtém o nome da categoria selecionada, se houver
    categoria_nome = None
    if categoria_selecionada:
        categoria = get_object_or_404(Categoria, id=categoria_selecionada)
        categoria_nome = categoria.nome

    # Renderiza o template com os dados
    return render(request, 'estoque/itens_vencidos.html', {
        'itens_vencidos': page_obj,  # Envie a página em vez da queryset completa
        'categorias': categorias,
        'itens_por_categoria': itens_por_categoria,
        'total_itens_vencidos_categoria': total_itens_vencidos_categoria,
        'categoria_nome': categoria_nome,  # Adiciona o nome da categoria ao contexto
        'page_obj': page_obj,  # Passa o objeto da página para o template
        'categoria_selecionada': categoria_selecionada,  # Passa a categoria selecionada para o template
    })


class AlimentoListView(ListView):
    model = Alimento
    template_name = 'estoque/estoque.html'
    context_object_name = 'alimentos'
    paginate_by = 10  # Defina o número de alimentos por página

    def get_queryset(self):
        queryset = Alimento.objects.filter(validade__gte=timezone.now().date())  # Filtra para incluir apenas alimentos não vencidos

        # Filtros
        categoria_id = self.request.GET.get('categoria') or self.request.session.get('categoria_selecionada')
        if categoria_id:
            queryset = queryset.filter(categoria_id=categoria_id)

        nome = self.request.GET.get('nome')
        if nome:
            queryset = queryset.filter(nome__icontains=nome)

        referencia = self.request.GET.get('referencia')
        if referencia:
            queryset = queryset.filter(referencia__icontains=referencia)

        nro_nota = self.request.GET.get('nro_nota')
        if nro_nota:
            queryset = queryset.filter(nro_nota__icontains=nro_nota)

        marca = self.request.GET.get('marca')
        if marca:
            queryset = queryset.filter(marca__icontains=marca)

        nome_fornecedor = self.request.GET.get('nome_fornecedor')
        if nome_fornecedor:
            queryset = queryset.filter(nome_fornecedor__icontains=nome_fornecedor)

        return queryset.order_by('nome')  # Ordena por nome

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now().date()
        alimentos_vencidos = Alimento.objects.filter(validade__lt=now)

        context['categorias'] = Categoria.objects.all()  # Passa todas as categorias
        context['now'] = now  # Passa a data atual

        # Verificando se há alimentos vencidos para a notificação e se a mensagem já foi exibida
        total_vencidos = alimentos_vencidos.count()
        mensagem_vista = self.request.session.get('mensagem_vista', False)

        if total_vencidos > 0 and not mensagem_vista:
            context['mensagem_vencidos'] = f"Atenção: Você possui {total_vencidos} alimento(s) vencido(s). Por favor, visualize a área de ITENS VENCIDOS."
            self.request.session['mensagem_vista'] = True  # Marca que a mensagem já foi visualizada
        else:
            context['mensagem_vencidos'] = None  # Limpa a mensagem se não houver alimentos vencidos ou se a mensagem já foi visualizada

        # Calculando o valor total por categoria
        categoria_id = self.request.GET.get('categoria') or self.request.session.get('categoria_selecionada')

        if categoria_id:
            context['valor_total_categoria'] = Alimento.objects.filter(categoria_id=categoria_id).aggregate(Sum('valor'))['valor__sum'] or 0
            context['categoria_atual'] = Categoria.objects.get(id=categoria_id).nome  # Adiciona o nome da categoria atual
            context['categoria_selecionada'] = categoria_id  # Passa a categoria selecionada para o template

            # Armazenar a categoria na sessão
            self.request.session['categoria_selecionada'] = categoria_id
        else:
            context['valor_total_categoria'] = 0
            context['categoria_atual'] = "Nenhuma Categoria Selecionada"  # Indica que nenhuma categoria foi escolhida
            context['categoria_selecionada'] = None  # Nenhuma categoria foi selecionada

        return context


class AlimentoCreateView(CreateView):
    model = Alimento
    form_class = AlimentoForm
    template_name = 'estoque/alimento_create.html'
    success_url = reverse_lazy('alimento_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()  # Supondo que você tenha um modelo Categoria
        return context

    def form_valid(self, form):
        # Captura os dados dos campos
        categoria = form.cleaned_data.get('categoria')
        nome = form.cleaned_data.get('nome')
        referencia = form.cleaned_data.get('referencia')
        quantidade = form.cleaned_data.get('quantidade')
        peso = form.cleaned_data.get('peso')
        validade = form.cleaned_data.get('validade')
        nro_nota = form.cleaned_data.get('nro_nota')
        nome_fornecedor = form.cleaned_data.get('nome_fornecedor')
        marca = form.cleaned_data.get('marca')
        valor = form.cleaned_data.get('valor')  # Captura o valor do alimento

        # Verifica se o alimento com essa referência já existe no estoque
        alimento_existente = Alimento.objects.filter(nome=nome, referencia=referencia).first()

        if alimento_existente:
            # Incrementa a quantidade e o peso
            alimento_existente.quantidade += quantidade
            alimento_existente.peso += peso
            alimento_existente.save()

            # Registra a entrada do alimento existente
            entrada = Entrada(
                alimento=alimento_existente,
                quantidade=quantidade,
                peso=peso,
                validade=validade
            )
            entrada.save()

            # Atualiza o form para apontar para o alimento existente
            form.instance = alimento_existente
        else:
            # Salva o novo alimento com todos os campos
            alimento = form.save(commit=False)
            alimento.categoria = categoria  # Atribui a categoria ao novo alimento
            alimento.valor = valor  # Atribui o valor diretamente ao novo alimento
            alimento.save()

            # Registra a entrada do novo alimento
            entrada = Entrada(
                alimento=alimento,
                quantidade=quantidade,
                peso=peso,
                validade=validade
            )
            entrada.save()

        return super().form_valid(form)




class AlimentoUpdateView(UpdateView):
    model = Alimento
    form_class = AlimentoForm
    template_name = 'estoque/alimento_update.html'
    success_url = reverse_lazy('alimento_list')

    def form_valid(self, form):
        # Atualiza todos os campos do alimento
        alimento = form.save(commit=False)

        quantidade_atualizada = form.cleaned_data.get('quantidade')

estoque/templates/estoque/alimento_create.html
{% extends 'base_estoque.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-1 mb-2 pb-2">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="post" class="p-4 rounded-3 border border-secondary shadow-sm" style="background: rgba(0, 0, 0, 0.7);">
                <h1 class="mb-4 text-center text-white fw-bold">Adicionar Alimento</h1>
                {% csrf_token %}
                
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_categoria" class="form-label text-white fw-bold">Categoria:</label>
                        <select name="categoria" class="form-control form-control-sm custom-input" style="background: rgba(255, 255, 255, 0.3); color: black;">
                            <option value="">Selecione:</option>
                            {% for categoria in categorias %}
                                <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="id_referencia" class="form-label text-white fw-bold">Referência:</label>
                        {{ form.referencia|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_nome" class="form-label text-white fw-bold">Nome:</label>
                        {{ form.nome|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_quantidade" class="form-label text-white fw-bold">Quantidade (Un):</label>
                        {{ form.quantidade|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_peso" class="form-label text-white fw-bold">Peso (Kg/L):</label>
                        {{ form.peso|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_validade" class="form-label text-white fw-bold">Validade:</label>
                        {{ form.validade|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_valor" class="form-label text-white fw-bold">Valor (Un):</label>
                        {{ form.valor|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_data_entrada" class="form-label text-white fw-bold">Data de Entrada:</label>
                        {{ form.data_entrada|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_nro_nota" class="form-label text-white fw-bold">Número da Nota:</label>
                        {{ form.nro_nota|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_nome_fornecedor" class="form-label text-white fw-bold">Nome do Fornecedor:</label>
                        {{ form.nome_fornecedor|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_marca" class="form-label text-white fw-bold">Marca:</label>
                        {{ form.marca|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="submit" class="btn btn-outline-success me-md-2">Adicionar</button>
                    <a href="{% url 'alimento_list' %}" class="btn btn-outline-danger">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
.custom-input {
    height: 40px; /* Ajuste a altura conforme necessário */
}
</style>
{% endblock %}

estoque/templates/estoque/alimento_update.html
{% extends 'base_estoque.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-1 mb-2 pb-2">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="post" class="p-4 rounded-3 border border-secondary shadow-sm" style="background: rgba(0, 0, 0, 0.7);">
                <h1 class="mb-4 text-center text-white fw-bold">Editar Alimento</h1>
                {% csrf_token %}
                
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_categoria" class="form-label text-white fw-bold">Categoria:</label>
                        <select name="categoria" class="form-control form-control-sm custom-input" style="background: rgba(255, 255, 255, 0.3); color: black;">
                            <option value="">Selecione:</option>
                            {% for categoria in categorias %}
                                <option value="{{ categoria.id }}" {% if categoria.id == form.categoria.value %}selected{% endif %}>{{ categoria.nome }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label for="id_referencia" class="form-label text-white fw-bold">Referência:</label>
                        {{ form.referencia|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_nome" class="form-label text-white fw-bold">Nome:</label>
                        {{ form.nome|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_quantidade" class="form-label text-white fw-bold">Quantidade:</label>
                        {{ form.quantidade|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_peso" class="form-label text-white fw-bold">Peso (Kg):</label>
                        {{ form.peso|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_validade" class="form-label text-white fw-bold">Validade:</label>
                        {{ form.validade|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_valor" class="form-label text-white fw-bold">Valor:</label>
                        {{ form.valor|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_data_entrada" class="form-label text-white fw-bold">Data de Entrada:</label>
                        {{ form.data_entrada|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_nro_nota" class="form-label text-white fw-bold">Número da Nota:</label>
                        {{ form.nro_nota|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                    <div class="col-md-6">
                        <label for="id_nome_fornecedor" class="form-label text-white fw-bold">Nome do Fornecedor:</label>
                        {{ form.nome_fornecedor|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="id_marca" class="form-label text-white fw-bold">Marca:</label>
                        {{ form.marca|add_class:"form-control form-control-sm custom-input" }}
                    </div>
                </div>
                
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="submit" class="btn btn-outline-success me-md-2">Atualizar</button>
                    <a href="{% url 'alimento_list' %}" class="btn btn-outline-danger">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
.custom-input {
    height: 40px; /* Ajuste a altura conforme necessário */
}
</style>
{% endblock %}

estoque/templates/estoque/entradas_list.html
{% extends 'base_estoque.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <nav id="sidebar" class="col-md-2 d-md-block bg-dark text-light p-0">
            <div class="position-sticky">
                <h4 class="text-light text-center mt-3 p-2 fw-bold">Gestão de Estoque</h4>
                <div class="nav flex-column px-2">
                    <button class="btn btn-outline-primary mb-2" onclick="location.href='{% url 'alimento_list' %}'">
                        <i class="bi bi-box-seam"></i> Início
                    </button>
                    <button class="btn btn-outline-primary mb-2" onclick="location.href='{% url 'saidas_list' %}'">
                        <i class="bi bi-box-seam"></i> Saídas
                    </button>
                    <button class="btn btn-outline-warning mb-2" onclick="location.href='{% url 'financeiro' %}'">
                        <i class="bi bi-box-seam"></i> Financeiro
                    </button>
                    <button class="btn btn-outline-danger mb-2" onclick="location.href='{% url 'itens_vencidos' %}'">
                        <i class="bi bi-box-seam"></i> Itens Vencidos
                    </button>
                    <button class="btn btn-outline-secondary mb-2" onclick="location.href='{% url 'deslogar' %}'">
                        <i class="bi bi-door-open"></i> Sair da Aplicação
                    </button>
                </div>
            </div>
        </nav>

        <!-- Main content -->
        <main class="col-md-10 ms-sm-auto px-md-4 mt-4">
            <h2>Lista de Entradas</h2>

            <form method="GET" class="mb-3">
                <div class="input-group">
                    <select name="categoria" class="form-select form-select-sm me-2">
                        <option value="">Filtrar por Categoria</option>
                        {% for categoria in categorias %}
                            <option value="{{ categoria.id }}" {% if categoria.id == request.GET.categoria|default:"" %}selected{% endif %}>{{ categoria.nome }}</option>
                        {% endfor %}
                    </select>
                    <input type="date" name="data_inicio" class="form-control form-control-sm me-2" placeholder="Data Início" value="{{ request.GET.data_inicio }}">
                    <input type="date" name="data_fim" class="form-control form-control-sm me-2" placeholder="Data Fim" value="{{ request.GET.data_fim }}">
                    <input type="text" name="referencia" class="form-control form-control-sm me-2" placeholder="Referência do Produto" value="{{ request.GET.referencia }}">
                </div>
            </form>

            <!-- Botões abaixo dos filtros -->
            <div class="mb-3 d-flex justify-content-start">
                <button class="btn btn-outline-primary btn-sm me-2" type="submit" onclick="document.forms[0].submit()">Filtrar</button>
                <button class="btn btn-outline-secondary btn-sm me-2" onclick="location.href='{{ request.path }}'">
                    Limpar Filtros
                </button>
                {% comment %} <button class="btn btn-outline-success btn-sm" onclick="location.href='{% url 'entradas_pdf' %}'">
                    <i class="bi bi-file-earmark-pdf"></i> Gerar PDF
                </button> {% endcomment %}
            </div>


            <!-- Tabela de entradas -->
            <table class="table table-dark table-bordered table-striped">
                <thead class="thead-light">
                    <tr>
                        <th>Alimento</th>
                        <th>Quantidade</th>
                        <th>Peso</th>
                        <th>Validade</th>
                        <th>Data de Registro</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entrada in entradas %}
                    <tr>
                        <td>{{ entrada.alimento.nome }}</td>
                        <td>{{ entrada.quantidade }}</td>
                        <td>{{ entrada.peso }}</td>
                        <td>{{ entrada.validade }}</td>
                        <td>{{ entrada.data }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Nenhuma entrada registrada.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- Paginação -->
            <div class="d-flex justify-content-between align-items-center mt-3">
                <div>
                    <span class="text-light">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
                </div>
                <nav>
                    <ul class="pagination pagination-sm">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">Primeira</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                            </li>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active" aria-current="page">
                                    <span class="page-link">{{ num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}{% if request.GET.categoria %}&categoria={{ request.GET.categoria }}{% endif %}{% if request.GET.nome %}&nome={{ request.GET.nome }}{% endif %}{% if request.GET.referencia %}&referencia={{ request.GET.referencia }}{% endif %}{% if request.GET.data_entrada %}&data_entrada={{ request.GET.data_entrada }}{% endif %}{% if request.GET.nro_nota %}&nro_nota={{ request.GET.nro_nota }}{% endif %}{% if request.GET.marca %}&marca={{ request.GET.marca }}{% endif %}{% if request.GET.nome_fornecedor %}&nome_fornecedor={{ request.GET.nome_fornecedor }}{% endif %}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Próxima</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>

        </main>
    </div>
</div>
{% endblock %}